#!/bin/bash

cat > TEMPIN <<EOF
    4 3                   # number of inputs and neurons
    1.5  1.8  2.4  8.1    # all inputs on a single line
    0.5  0.1  0.2         # weights from first  input (to each neuron)
    0.4  0.1  0.2         # weights from second input (to each neuron)
    0.3  0.1  0.2         # weights from third  input (to each neuron)
    0.2  0.1  0.2         # weights from fourth input (to each neuron)
EOF

/usr/bin/time -p  ./p6 TEMPIN
